apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quakewatch
            image: soulgamer/quakewatch:latest
            command: ["echo", "Running QuakeWatch CronJob"]
          restartPolicy: OnFailure

