apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: quakewatch
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
