apiVersion: v1
entries:
  quakewatch-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-09-14T15:13:29.554871+03:00"
    description: A Helm chart for Kubernetes
    digest: 950f0bb2e68e571ecfc97d23116c1adecae111294bf43c06ad6e94d5b7d6ef4f
    name: quakewatch-chart
    type: application
    urls:
    - https://<YOUR_GITHUB_USERNAME>.github.io/QuakeWatch/charts/quakewatch-chart-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-14T15:13:29.552379+03:00"
