apiVersion: v1
kind: Service
metadata:
  name: quakewatch-service
spec:
  selector:
    app: quakewatch
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002

